### ISSUE TITLE
Result is just a single value

### ISSUE THREAD

**Issue by berkanttubi** [trichter/xcorr#1]
Are there any size restriction for the signal in the code ? It is perfectly working on my big dataframe shapes like (10000,1) but when I decrease the size to (400,1) it is giving me only a single value... Can anyone help?

**Comment by trichter** [comment]
No, there are not any size restrictions.

Which of the two functions do you call in which way? Can you provide a minimal reproducing code example of your problem?

**Comment by berkanttubi** [comment]
Okay, the problem is solved. It was about the dimension I guess. The code is working fine, sorry :). Thank you!

**Comment by berkanttubi** [comment]
This one is not working... I am just getting a single value...
![image](https://user-images.githubusercontent.com/37797429/125285506-643cd180-e323-11eb-8c1e-3076c11126be.png)

This one is working... It is about the having same size I think... Can we do something about it?
![image](https://user-images.githubusercontent.com/37797429/125285837-bda50080-e323-11eb-98a7-f0991396a06a.png)

**Comment by trichter** [comment]
That is expected for arrays of equal length. You have two options. Either switch from `mode='valid'` to `mode='same'` or `mode='full'` or use the `correlate_maxlag` function to specify the number of samples in the cc. Please have a look at the doc strings in the source code.
